import type {Metadata} from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Trending from "./components/Trending";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[80%] mx-auto border-2 border-white min-h-screen">
        <div className="flex border-2 border-yellow-300">
          <div className="basis-1/4 border-2 border-red-500">
            <Sidebar />
          </div>
          <div className="basis-2/4">{children}</div>
          <div className="basis-1/4 border-2 border-green-500 h-full">
            <Trending />
          </div>
        </div>
      </body>
    </html>
  );
}
